[pytest]
python_files = tests.py test_*.py *_tests.py
addopts =
    --doctest-modules
    --ignore-glob=bin/*
    --ignore-glob=data/*
    --ignore-glob=docker/*
    --ignore-glob=exemplos/*
    --ignore-glob=scripts/*
    -vvvs
